sudo: true
dist: trusty
services:
   - docker
language: python
python:
   - '3.5'
before_install:
   - "pip install 'lander>=0.1.0,<0.2'"
script:
   # Compile PDF using containerized lsst-texmf
   - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
   # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
   - "lander --version"
   - "echo $TRAVIS_PULL_REQUEST"
   - "lander --pdf ${PRODUCT}.pdf --upload --lsstdoc ${PRODUCT}.tex --env=travis --ltd-product $PRODUCT --docushare-url $DOCUSHAREURL"
env:
  global:
    - PRODUCT="LDM-135"
    - DOCUSHAREURL="https://ls.st/ldm-135*"
    # LSST the Docs credentials
    - secure: "IyLCzKp8DDjxFskmmDGWV6IRx5cAOooVG2r/QosVMRqPyx8xAHYh+0w8NToOYcsP5S5OeU6qMb+LWwD/AnEXpOU+kI/bI7LZq68pDPgr1swrrgsbL9hInfkTKE5mI6WedqYF3MKUZ0hkp5WgaFScR75HRvaYlgupEMln003i4AamL8eJIW0P7galzxUIQnteDBzGgCSwf9IZsRJy0UhAW3Sllx04vpeHuC0oXG4nR2RsW7edub8HnQ+fTyZZ0UbPqwMB8WQYKs/CmA/GRM+8VYSZolLOGeIjtIg3j0Yh7W6xe/7czFyLrbE8Hr4OshuI/S8/rV7SXloI30hOwlG6PehNT4u4/xYrDdlJq2ua6fPjkE24B22QxPzs/CB7HIRhrxpBv2RZfelqc67bj+Bm4xAhlhScdlWRcZ7/b1d38/BQRStneCQ+XSxjnR48MxB2C3xN6+Bl9qfRUrNN+1gm8N2HOE0XfZ+spi6XKUIkYtKlWLPqqZO0TjCzN1PMOLETqHM3ZIWZdmwsVWtlAMHJ3Ox2wP3XylSqhbqHerzAuqbPu0ZU5cB4TAslfnBDjtWqhkFdrL6zPCh/ASXCKluU13F60WtOlan+/vaTGSC1/lMx91Zo7GyjcyT4G7GkC6RFG1skZetXjzOGhRWyOUGdYBPCNPntBb//SL783NoQkIQ="
    - secure: "iKM6mNziaRS2a/3vaDBCfmA9LCgqgIzsvaADP5Poebo2xgyhwaWfzw90NynIpvQn+PeZ9wiUqpYq44JZEj45/RilfqaVev3kh8D+z81noP9WhYs8mskj/OSx4HHaBU6jxeHH5mOjXXusyjjhh2Jtx/9AuZtiRCzHtJMRkNivlrINP+tRekEhBJ1adzD0kHpXZJDuXggQ9JZjM3Cx3FAXIUODV5JTp11kHuAmy+s22Fxvr27PhlMoL2GdfGY911832+GN7KYt0LpXNqkcG4RE0Am+RxOpgiz+rOxCNJCTd6uKEeRXcb5FDVqk/mqmiAcUCSg7gjbYjxRBAiAkHY+rfBu+ierEAzqeL/xBNG9p8qc0BliTkukhTfDOD9B8Oxa7gXu53gsY5TaJMGjRJeDaa9856G02dH3HgG34SYWOc86zlxThL5KcL5Xd/F01nPu2NFRsOcdW9OQAGiwfD9LsfzpHP5uvlUAvcHTnaY0SfQb3K8Qm3dea7FikoLwnGl3wTJSerBiM1EIFJERHhrvYntdRG/rsHj+3BLig/7PwPwrT2ogPy/T15U0iYD4TC6Y9juef9pTnIV6CKyk8/WSddMTVOyE6dTdl4sK2smr4MCwX5K+NuB9ZY3qCQqP2V1eshxX/57MSp8qbME+n/RpaSOdWEJAjzu+C+LgyNxgg/8Y="
